# build java
language: java
jdk:
  - oraclejdk8

#use docker
sudo: required
services:
  - docker

after_success:
  - docker login -e="yuri.a.melnikov@gmail.com" -u="anubisdocker" -p="K1_argador"
  - docker build -t=anubisdocker/rest-server:latest .

